# @name singup
POST {{endpoint}}/api/user
Content-Type: application/json

{
  "name": "test-user",
  "email": "test-email",
  "password": "test-password"
}
###

# @name login
POST {{endpoint}}/api/user/login
Content-Type: application/json

{
  "email": "test-email",
  "password": "test-password"
}
###

# @name logout
POST {{endpoint}}/api/user/logout
Content-Type: application/json
Authorization: Bearer USER-2e1f5cf5-35d8-40d0-a5f1-0b762df16106:d3GZVtFqH959DSXbXWCivWBEwt5PZkyRGUfxJF5ke23njc8v4qP7FDdcPZzAA6jI0AKSyym8tHWUPMRk6jqH78xz14tSndzRGrktKMmDp8fpUDBv9qEvAxxog1kzW7pL

{}
###
